# Copyright 2025 Paul-van-Klaveren
# https://github.com/manna-harbour/miryoku

name: '❊ splitkb_aurora_sweep nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_sweep_left nice_view_adapter nice_view","splitkb_aurora_sweep_right nice_view_adapter nice_view","settings_reset"]'
      clipboard: '["mac"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'
